#!/usr/bin/env python
import os
import subprocess
import sys
import yaml

with open(sys.argv[1]) as f:
    cfg = yaml.safe_load(f)
    output = {
        "apiVersion": "v1",
        "kind": "Secret",
        "metadata": cfg.get("metadata"),
        "stringData": {},
    }
    data = output["stringData"]

    for filename in cfg.get("envs", []):
        decrypted = subprocess.check_output(
            ["sops", "--input-type", "dotenv", "--decrypt", filename]
        ).decode()
        for line in decrypted.splitlines():
            if line.startswith('#') or not line.strip():
                continue
            k, v = line.split("=")
            data[k] = v

    for filename in cfg.get("files", []):
        if "=" in filename:
            key, filename = filename.split("=")
        else:
            key = filename

        key = os.path.basename(key)

        data[key] = subprocess.check_output(
            ["sops", "--decrypt", filename]
        )

    for line in cfg.get("literals", []):
        k, v = line.split("=")
        data[k] = v

    print(yaml.dump(output))
